@startuml
start
:User executes import command;

if () then ([valid csv])
    :Parse rows in CSV file;
    :Creates a valid list of person to be imported;
    :Read from valid list of person;
    :Add list of person to current address book;
else ([invalid csv])
endif
stop
@enduml
