@startuml

!include style.puml

box Logic LOGIC_COLOR
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response


end box



box Model MODEL_COLOR


@enduml
